---
########################################
# Initialisation script for the seeding process
- hosts: game_server

  # Stops gathering machine variables, allows for faster execution.
  gather_facts: false

  become: true
  become_method: sudo
  become_user: root

  roles:
    #- configuration
    #- swarm
    #- minecraft-service
    - battlefield2-service
