---
########################################
# Update all packages to their latest version
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

########################################
# Install required dependencies
- name: Install dependencies
  package:
    name:
      - ufw
      - docker.io
      - python3-docker
    state: present

########################################
# Remove non required dependencies
- name: Remove non required dependencies
  apt:
    autoremove: yes

########################################
# Configure UFW
- name: Configure UFW
  ufw:
    rule: "{{ item.rule }}"
    proto: "{{ item.protocol }}"
    port: "{{ item.port }}"
    comment: "{{ item.comment }}"
  with_items:
    - { rule: allow, protocol: tcp, port: "22", comment: "SSH access for administrators" }
    - { rule: allow, protocol: tcp, port: "9090", comment: "HTTPS port for cockpit" }
    - { rule: allow, protocol: tcp, port: "25565", comment: "TCP port for minecraft" }
