---
########################################
# Install required dependencies
- name: Install swarm dependencies
  package:
    name:
      - docker.io
      - python3-docker
    state: present
  
########################################
# Start and enable the docker daemon
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

########################################
# Initialise a default swarm
- name: Initialise a new swarm
  docker_swarm:
    state: present

########################################
# Remove all services
- name: Remove services if present
  docker_swarm_service:
    name: "{{ item }}"
    state: absent
  loop:
    - minecraft-service
    - battlefield2-service

########################################
# Create swarm network for minecraft
- name: Create a network with options
  docker_network:
    name: GamingOverlay
    driver: overlay
    driver_options:
      encrypted: true
